### ISSUE TITLE
List of improperly styled places

### ISSUE THREAD

**Issue by VFDan** [VFDan/Scratch-Dark-Theme#8]
+ #9
+ The 60 second thing.
![image](https://user-images.githubusercontent.com/44413950/89833745-905a3c00-db2f-11ea-8a87-3cca9df5dc51.png)
+ Changing Language
![image](https://user-images.githubusercontent.com/44413950/90830550-d8d3df80-e30f-11ea-8cd3-ce342625d87d.png)

**Comment by VFDan** [comment]
And it's public!

**Comment by MiniCoder11** [comment]
@VFDan Hooray!!!

**Comment by VFDan** [comment]
updated

**Comment by MiniCoder11** [comment]
Okay, I'll fix it. I saw that yesterday and was hoping that you wouldn't notice : ) Also, I added support for Griffpatch's DevTools extension.

**Comment by MiniCoder11** [comment]
@VFDan CSS is being picky and I can't select the text color from any of the tags that Scratch assigns.

**Comment by VFDan** [comment]
Wait, can styling be applied into iframes with CSS? Because the preview is an iframe...

> I saw that yesterday and was hoping that you wouldn't notice
I go on the forums a lot :P

**Comment by VFDan** [comment]
Found a relevant SO post: https://stackoverflow.com/a/7571138/ so we can actually style

**Comment by VFDan** [comment]
I made it a seperate issue, #9.

**Comment by VFDan** [comment]
Updated.

**Comment by VFDan** [comment]
updated

**Comment by MiniCoder11** [comment]
I'll work on it but my priorities are currently focused on this: [ScratchTools](https://github.com/MiniCoder11/ScratchTools).

**Comment by VFDan** [comment]
Nah it's fine, you don't have to work on it if you don't want to.

**Comment by MiniCoder11** [comment]
> 
> 
> Nah it's fine, you don't have to work on it if you don't want to.

I'll get around to it soon because it will make the dark theme in my extension easier to implement 😄

**Comment by MiniCoder11** [comment]
I'll try to fix the bugs this weekend.
